---
apiVersion: v1
kind: Secret
metadata:
  name: <secretname>
  annotations:
    tekton.dev/docker-0: <registry urls> # hosted registry urls https://abc.example.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>

---
apiVersion: v1
kind: Secret
metadata:
  name: <secretname>
  annotations:
    tekton.dev/git-0: <git urls> # hosted git urls https://git.example.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <sa-name>
secrets:
- name: <git-secret>
- name: <docker-secret>
imagePullSecrets:
- name: <docker-secret>
