---
apiVersion: v1
kind: Secret
metadata:
  name: <secretname>
  annotations:
    tekton.dev/docker-0: <registry urls> # hosted registry urls https://abc.example.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
