---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  # parameters 
  params:
  - name: buildRevision
  - name: appGitUrl
  - name: appImage
  
  # workspaces
  workspaces:
  - name: app-source
   
  # steps
  steps:
  - name: clone
    image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:dc64f60840f12168420cdc7248cafbefc56b11f509cb7532819db8af910e8273
    workingDir: "$(workspaces.app-source.path)"
    env:
    - name: PARAM_URL
      value: $(params.appGitUrl)
    - name: PARAM_REVISION
      value: $(params.buildRevision)
    - name: WORKSPACE_OUTPUT_PATH
      value: $(workspaces.app-source.path)
      

# scripts
    script: |
      export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
      CHECKOUT_DIR="${WORKSPACE_OUTPUT_PATH}"
      rm -rf "$CHECKOUT_DIR"/*
      rm -rf "$CHECKOUT_DIR"/.[!.]*
      rm -rf "$CHECKOUT_DIR"/..?*
      cd "$CHECKOUT_DIR"
      git clone --branch "${PARAM_REVISION}" "${PARAM_URL}"
      var1=$(echo "${PARAM_URL}" | awk '{split($0,a,"/");print a[5]}')
      echo $var1
      var2=$(echo $var1 | awk '{split($0,a,".");print a[1]}')
      echo $var2
      mv $var2/* ${WORKSPACE_OUTPUT_PATH}
      rm -rf $var2
      git config --global user.name "tkn pipelines"
      git config --global user.email "you@example.com"
      ls "$CHECKOUT_DIR"
      
  - name: build
    image: quay.io/buildah/stable:v1.28.0
    workingDir: "$(workspaces.app-source.path)"
    command: ['buildah', 'bud', 'format=oci', '--tls-verify=false', '--layers', '-f', 'Dockerfile', '-t', '$(params.appImage):$(params.buildRevision)', '.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
      
  - name: push
    image: quay.io/buildah/stable:v1.28.0
    command: ["buildah", "push", "--tls-verify=false", "$(params.appImage):$(params.buildRevision)", "docker.io//$(params.appImage):$(params.buildRevision)"]
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
      
  volumes:
  - name: varlibcontainers
    emptyDir: {}
