---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-cicd-role
  namespace:
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-sa-role-binding
  namespace:
subjects:
- kind: ServiceAccount
  name: tekton-cicd-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-cicd-role
  
  
  
  
